{
 "title": "r1-BDVA",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "所有车辆的速度变化",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "BusId::tag" ], "type": "tag" }
     ],
     "measurement": "BusStatus",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "汽车速度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "measurement": "BusStatus",
     "query": "SELECT mean(\"value\") FROM \"BusStatus\" WHERE (\"BusId\"::tag = 'select tag value') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "BusId::tag", "operator": "=", "value": "B01" }
     ]
    }
   ]
  },
  {
   "title": "所有车辆的速度变化",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "BusId::tag" ], "type": "tag" }
     ],
     "measurement": "BusStatus",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "运行轨迹",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "measurement": "BusStatus",
     "query": "SELECT \"Latitude\" FROM \"BusStatus\" WHERE (\"BusId\"::tag = 'B01') AND $timeFilter",
     "select": [
      [
       { "params": [ "Latitude" ], "type": "field" }
      ],
      [
       { "params": [ "Longitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "BusId::tag", "operator": "=", "value": "B01" }
     ]
    },
    {
     "measurement": "BusStatus",
     "select": [
      [
       { "params": [ "Latitude" ], "type": "field" }
      ],
      [
       { "params": [ "Longitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "BusId::tag", "operator": "=", "value": "B02" }
     ]
    }
   ]
  },
  {
   "title": "当前速度",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "BusId::tag" ], "type": "tag" }
     ],
     "measurement": "BusStatus",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}